# Generated by Django 2.0.3 on 2018-03-23 16:13
#ADETUNJI KAYODE
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_date', models.DateField()),
                ('geo', models.CharField(max_length=100)),
                ('commod', models.CharField(max_length=100)),
                ('vector', models.CharField(max_length=100)),
                ('coordinate', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
    ]
