# Generated by Django 2.0.3 on 2018-03-23 16:36
#ADETUNJI KAYODE

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
